// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Signify",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Signify",
            targets: ["AppModule"],
            bundleIdentifier: "com.Signify.SwiftStudentChallenge",
            teamIdentifier: "B6QMD2854G",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .coffee),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "MyApp uses the camera to identify landmarks as you explore new places.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resource/MyHandPoseClassifier.mlmodelc") // copy resources to the app bundle without keeping folder structure
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
